# ----------------------------------------------------------------------------------------------------------------------
# Artemis-Prod-MySQL Setup
# ----------------------------------------------------------------------------------------------------------------------

# this links to /docker/artemis-prod-mysql.yml which is the default artemis production docker compose setup

# BUILD IMAGE / LOCALVC - LOCALCI
services:
    artemis-app:
        extends:
            file: ./artemis-prod-mysql.yml
            service: artemis-app
    mysql:
        extends:
            file: ./artemis-prod-mysql.yml
            service: mysql
    nginx:
        extends:
            file: ./artemis-prod-mysql.yml
            service: nginx

networks:
    artemis:
        driver: "bridge"
        name: artemis
volumes:
  artemis-mysql-data:
    name: artemis-mysql-data
  artemis-data:
    name: artemis-data

# PRODUCT

#services:
#  artemis-app:
#    image: azurexen/artemis-app:latest
#    container_name: artemis-app
#    volumes:
#      - ./artemis-data:/opt/artemis/data
#    expose:
#      - "8080"
#      - "5701"
#      - "7921"
#    restart: on-failure:3
#    networks:
#      - artemis
#    environment:
#      ARTEMIS_ATHENA_SECRET: "abcdefg12345"
#      ARTEMIS_USERMANAGEMENT_INTERNALADMIN_PASSWORD: "artemis_admin"
#      ARTEMIS_USERMANAGEMENT_INTERNALADMIN_USERNAME: "artemis_admin"
#      ARTEMIS_USERMANAGEMENT_USEEXTERNAL: "false"
#      JHIPSTER_REGISTRY_PASSWORD: "AN-ADMIN-PASSWORD-THAT-MUST-BE-CHANGED (FROM REGISTRY CONFIG)"
#      JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64SECRET: "bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo="
#      SPRING_DATASOURCE_PASSWORD: "Thereisapotato!"
#      SPRING_DATASOURCE_URL: "jdbc:mysql://artemismysql.mysql.database.azure.com:3306/artemis"
#      SPRING_DATASOURCE_USERNAME: "artemis_admin"
#      SPRING_MAIL_PASSWORD: ""
#      SPRING_MAIL_USERNAME: ""
#      SPRING_PROFILES_ACTIVE: "artemis,jenkins,scheduling,athena,core,prod,docker"
#      SPRING_WEBSOCKET_BROKER_PASSWORD: "guest"
#      SPRING_WEBSOCKET_BROKER_USERNAME: "guest"
#
#  nginx:
#    image: azurexen/artemis-nginx:latest
#    container_name: artemis-nginx
#    ports:
#      - "80:80"
#      - "443:443"
#      - "7921:7921"
#    volumes:
#      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx-config/timeouts.conf:/etc/nginx/conf.d/timeouts.conf:ro
#      - ./nginx-config/artemis-nginx.conf:/etc/nginx/conf.d/artemis-nginx.conf:ro
#      - ./nginx-config/artemis-upstream-single-node.conf:/etc/nginx/includes/artemis-upstream.conf:ro
#      - ./nginx-config/artemis-ssh-upstream-single-node.conf:/etc/nginx/includes/artemis-ssh-upstream.conf:ro
#      - ./nginx-config/artemis-server.conf:/etc/nginx/includes/artemis-server.conf:ro
#      - ./nginx-config/dhparam.pem:/etc/nginx/dhparam.pem:ro
#      - ./nginx-config/nginx_503.html:/usr/share/nginx/html/503.html:ro
#      - ./nginx-config/70-artemis-setup.sh:/docker-entrypoint.d/70-artemis-setup.sh:ro
#      - ./nginx-config/artemis-nginx+4.pem:/certs/fullchain.pem:ro
#      - ./nginx-config/artemis-nginx+4-key.pem:/certs/priv_key.pem:ro
#    depends_on:
#      artemis-app:
#        condition: service_started
#    restart: on-failure:3
#    networks:
#      - artemis
#
#networks:
#  artemis:
#    driver: "bridge"
#    name: artemis

## DEVELOPMENT
#version: "3"
#
#services:
#  artemis-app:
#    image: azurexen/artemis-app:latest
#    container_name: artemis-app
#    ports:
#      - "8080:8080"
#      - "5005:5005"
#    expose:
#      - "5005"
#    restart: on-failure:3
#    networks:
#      - artemis
#    environment:
#      SPRING_PROFILES_ACTIVE: artemis,scheduling,athena,core,dev,docker
#      SPRING_DATASOURCE_PASSWORD: "Thereisapotato!"
#      SPRING_DATASOURCE_URL: "jdbc:mysql://artemismysql.mysql.database.azure.com:3306/artemis"
#      SPRING_DATASOURCE_USERNAME: "artemis_admin"
#      _JAVA_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
#networks:
#  artemis:
#    driver: "bridge"
#    name: artemis


